Close #31, add zip row to table. Tweak and improve css.
SuffolkLITLab/docassemble-AssemblyLine pull request #183
Opened 2021-06-08 19:34 UTC by plocket

Closes #31 if accepted. It's one way to do it. I abstracted a little differently, so let me know if you want to chat about it.

Now that there was longer text to see in the title cell, the buttons arrangement wasn't looking as good, so I tweaked that css a bit.

2021-06-08 21:15 UTC, BryceStevenWilley commented on docassemble/AssemblyLine/al_document.py
> +def table_row( title:str, buttons:list = []) -> str:
```suggestion
def table_row( title:str, button_htmls:List[str] = []) -> str:
```
Just would make it a bit easier to understand at first glance.

2021-06-09 17:39 UTC, nonprofittechy requested changes
The .zip file should contain each assembled template as a separate file, not a single PDF that combines all documents. I suggest both Word and PDF format if the original is not a PDF.

We should also make turning it on/off a parameter.

2021-06-09 21:31 UTC, plocket commented
Ready for a second review

2021-06-10 00:05 UTC, nonprofittechy commented
Looks good, thanks!

2021-06-10 00:05 UTC, merged