Close #563 Add send email table row and change styling to align buttons
SuffolkLITLab/docassemble-AssemblyLine pull request #594
Opened 2022-10-05 18:59 UTC by plocket

Closes #563, Closes #562, alignment of document download table buttons vs. document email section parts, plus other alignment and styling issues. [I tried to limit the changes to the email section as people are using that styled as-is right now.] Here are some notes from our deep dive doc as well:

* Add a new parameter to download_list_html() to include a send email button row. But it will be a copy of the feature - we won’t delete the existing send_button_html() method.
* Fix the send_button_html() method html strings to remove the H5, though keep the styling
* Right align the send button of the separate email section,
* Remove the big gutter between the buttons and the text

Remade this PR because the pfs/black changes on the old branch caused a conflict with my updates.

Also closes #177 I believe.

2022-10-12 14:19 UTC, nonprofittechy commented on docassemble/AssemblyLine/al_document.py
> +        include an editable (Word) copy of the file, if it is available.
```suggestion
        include an editable (Word) copy of the file, if and only if it is available.
```
FYI, maybe I will avoid this shorthand but iff = if and only if--not the same as "if"

2022-10-12 14:25 UTC, nonprofittechy requested changes
This is a tricky task--and thanks for all of your work on it so far!

I like the look at various sizes, but on a standard mobile device, the text in the button is now wrapping, which is not very visually attractive:

![image](https://user-images.githubusercontent.com/7645641/195369284-fb562a1e-4443-48c6-b40f-ae01853840b8.png)

Maybe we can adjust the gutters to fix that? We should get it right at least on an iPhone 11 or newer.

On an iPhone 5, we have horizontal scrolling, which is also not ideal.

2022-10-12 14:27 UTC, nonprofittechy commented
One idea -- if it's just too hard to fit on mobile, maybe stack the form title and the view/download buttons vertically on mobile devices? We do need to really get that visual look right because it's a large proportion of our uses - 55%

2022-10-12 15:57 UTC, nonprofittechy commented
FYI, to avoid merge conflicts--pull this branch into your playground before making more changes.

2023-01-18 17:46 UTC, plocket commented
Not sure what we want to do with the pre-existing email elements because we said didn't want to change those too much, but this is what stuff looks like now at less than 576px (shown on Galaxy Fold):

<img width="206" alt="Screen Shot 2023-01-17 at 6 02 55 PM" src="https://user-images.githubusercontent.com/52798256/213247477-c356b766-4d13-414a-b836-c85e8d8e2167.png">

I put validation errors below the email input field instead of next to it:

<img width="190" alt="Screen Shot 2023-01-17 at 6 20 54 PM" src="https://user-images.githubusercontent.com/52798256/213247534-cf6f40f1-5871-46a6-ac85-40fffa20cd0c.png">

That leaves us with this problem on bigger screens that I'm still trying to figure out:

<img width="478" alt="Screen Shot 2023-01-18 at 12 41 16 PM" src="https://user-images.githubusercontent.com/52798256/213255049-aabe3ab6-cfe7-47d5-804b-4a4f625325aa.png">

Just fyi, I keep having problems with the browser inspector trying out devices - under some circumstances I get weird behavior, like needing to scroll when in phone mode or the elements becoming narrower than the screen. You might be running into this too.

Some width stuff has to be somewhat home-brewed (from what I can tell so far) because we have to handle more than just column widths. For example, aligning doc titles left instead of right. If someone knows how to do this through bootstrap, give a shout.

2023-01-18 19:15 UTC, BryceStevenWilley commented
Try merging with main, I fixed that error earlier last month, Github made a change in the underlying container I think

2023-01-18 23:11 UTC, plocket commented
Since this issue is about the download table, it may be worth leaving the isolated email component out of this PR and dealing with it in another issue.

2023-01-18 23:40 UTC, BryceStevenWilley commented
I'm not sure how you merged, but it unfortunately has muddled the diff; I'm not sure why all of the other changes are showing up in it now. You could revert the changes, and maybe try rebasing on main instead? You can make a copy of the branch (`git checkout -b doc_table_alignment_dupe`) before trying, just so you don't lose info

2023-01-18 23:45 UTC, plocket commented
Tried to rebase in GitHub, but it said there were conflicts. I'll try anyway.

2023-01-18 23:49 UTC, plocket commented
Seemed to work when rebasing locally. If the tests all pass, is it ok with folks if I force-push to this branch and this PR so that we can keep the PR comment history?

2023-02-27 16:26 UTC, merged