Experimenting with not running Kiln on non-functional commits
SuffolkLITLab/docassemble-AssemblyLine pull request #687
Opened 2023-05-08 14:53 UTC by BryceStevenWilley

Tests shouldn't need to run when change the README or the CHANGELOG.

2023-05-15 01:29 UTC, nonprofittechy commented
Does this stop kiln from re-running when you modify a .feature file? is that desired?

2023-05-15 01:50 UTC, nonprofittechy requested changes
Not sure this is a desirable or correct change

2023-05-15 14:05 UTC, BryceStevenWilley commented
> Does this stop kiln from re-running when you modify a .feature file?

No, this line should keep it running on anything in the actual package: `'docassemble/AssemblyLine/**'`. The `*.py` should keep it running on `setpy.py` or `__init__.py` files, that could break things (but really shouldn't).

2023-05-22 15:26 UTC, nonprofittechy commented on .github/workflows/run_form_tests.yml
> +      - 'docassemble/AssemblyLine/**'
```suggestion
      - 'docassemble/**'
```

2023-05-22 15:29 UTC, merged